<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.jmx.access.MBeanClientInterceptorTests" tests="12" skipped="0" failures="0" errors="0" timestamp="2019-12-09T02:20:51" hostname="DESKTOP-246NTI5" time="5.213">
  <properties/>
  <testcase name="testSetReadOnlyAttribute()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.03"/>
  <testcase name="testInvokeUnexposedMethodWithException()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.002"/>
  <testcase name="testSetAttributeValue()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.006"/>
  <testcase name="testTestLazyConnectionToRemote()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="5.131"/>
  <testcase name="testDifferentProxiesSameClass()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.005"/>
  <testcase name="testSetAttributeValueWithIOException()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.008"/>
  <testcase name="testGetAttributeValue()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.006"/>
  <testcase name="testInvokeNoArgs()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.004"/>
  <testcase name="testProxyClassIsDifferent()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.003"/>
  <testcase name="testInvokeArgs()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.005"/>
  <testcase name="testSetAttributeValueWithCheckedException()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.004"/>
  <testcase name="testSetAttributeValueWithRuntimeException()" classname="org.springframework.jmx.access.MBeanClientInterceptorTests" time="0.004"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[Dez 09, 2019 10:20:53 AM ClientCommunicatorAdmin restart
WARNUNG: Failed to restart: java.net.ConnectException: Connection refused: connect
Dez 09, 2019 10:20:54 AM ClientIntermediary close
INFORMATION: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

]]></system-err>
</testsuite>
